// Copyright 2022 Praetorian Security, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package scan

// These import statements ensure that the init functions run in each plugin.
// When a new plugin is added, this list should be updated.

import (
	// Fingerprinters for HTTP-based service detection
	_ "github.com/praetorian-inc/nerva/pkg/plugins/fingerprinters"

	// Standalone plugins for binary protocol detection
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/activemq"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/amqp"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/atg"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/bacnet"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/bgp"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/cassandra"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/crimsonv3"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/cups"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/db2"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/dhcp"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/diameter"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/diametersctp"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/dns"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/docker"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/echo"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/ethercat"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/ethernetip"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/firebird"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/fox"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/ftp"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/gesrtp"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/git"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/gtpc"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/gtpprime"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/gtpu"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/h323"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/hartip"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/http"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/iax2"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/iec104"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/ikev2"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/imap"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/influxdb"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/ipmi"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/ipp"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/ipsec"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/irc"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/iua"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/javarmi"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/jdwp"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/jetdirect"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/kafka/kafkaNew"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/kafka/kafkaOld"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/kerberos"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/knxip"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/l2tp"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/ldap"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/librechat"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/linuxrpc"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/m2ua"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/m3ua"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/megaco"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/melsecq"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/memcached"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/mgcp"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/milvus"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/modbus"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/mongodb"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/mqtt/mqtt3"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/mqtt/mqtt5"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/mssql"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/mysql"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/nats"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/neo4j"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/netbios"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/nfs"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/nrpe"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/ntp"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/omronfins"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/opcua"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/openvpn"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/oracledb"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/pcworx"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/pfcp"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/pop3"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/postgresql"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/pptp"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/proconos"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/profinet"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/pulsar"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/qdrant"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/rdp"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/redis"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/rsync"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/rtsp"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/s7comm"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/sccp"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/sgsap"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/sip"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/smb"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/smpp"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/smtp"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/snmp"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/snpp"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/socks4"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/socks5"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/sonarqube"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/ssh"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/stun"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/sua"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/svn"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/sybase"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/telnet"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/tftp"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/turn"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/unitronics"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/vnc"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/vmware"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/wireguard"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/x11"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/x2ap"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/xmpp"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/zabbix"
	_ "github.com/praetorian-inc/nerva/pkg/plugins/services/zookeeper"
)
